const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export function formatDate(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  const h = d.getHours() % 12 || 12;
  const m = String(d.getMinutes()).padStart(2, "0");
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}, ${String(h).padStart(2, "0")}:${m} ${d.getHours() < 12 ? "AM" : "PM"}`;
}

export function timeAgo(iso) {
  const secs = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000);
  if (secs < 60) return "just now";
  if (secs < 3600) return `${Math.floor(secs / 60)} min ago`;
  if (secs < 86400) return `${Math.floor(secs / 3600)} h ago`;
  return `${Math.floor(secs / 86400)} d ago`;
}

const slug = (text) => (text || "bug-repro").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export function downloadScript(report) {
  const url = URL.createObjectURL(new Blob([report.generatedScript], { type: "text/javascript" }));
  Object.assign(document.createElement("a"), { href: url, download: `${slug(report.title)}.spec.js` }).click();
  URL.revokeObjectURL(url);
}

export function toIssueMarkdown(report) {
  const steps = [...report.steps, ...(report.verificationStep ? [report.verificationStep] : [])];
  return `## 🐞 ${report.title || "Bug report"}

**Status:** ${report.verdict === "reproduced" ? "Reproduced automatically by ReproAI" : report.verdict === "not_reproduced" ? "Not reproduced" : "Run incomplete"}
**URL:** ${report.targetUrl}

### Reported by user
> ${report.bugDescription}

### Steps to reproduce
${steps.map((s, i) => `${i + 1}. ${s.description}`).join("\n")}

**Expected:** ${report.expectedResult || "-"}
**Actual:** ${report.actualResult || "-"}${report.observedResult ? `\n**Seen in browser:** \`${report.observedResult}\`` : ""}

### Playwright reproduction script
\`\`\`js
${report.generatedScript || ""}
\`\`\`

_Generated by ReproAI in ${(report.durationMs / 1000).toFixed(1)}s (${report.attempts} attempt${report.attempts === 1 ? "" : "s"})._
`;
}
